package projeto.hugo.terapia.professional.enumeracoes;

public enum Specialty
{
    PSICOLOGIA_CLINICA,
    PSICOLOGIA_ORGANIZACIONAL,
    PSICOLOGIA_ESCOLAR,
    PSICOLOGIA_JURIDICA,
    NEUROPSICOLOGIA,
    PSICOTERAPIA,
    PSICOLOGIA_SOCIAL,
    PSICOLOGIA_DA_SAUDE,
    PSICOLOGIA_INFANTIL,
    PSICOLOGIA_EDUCACIONAL
}
